# Generated by Django 4.1.1 on 2022-12-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('fecha', models.CharField(max_length=20)),
                ('proyecto', models.ManyToManyField(to='inicio.proyecto')),
            ],
        ),
    ]
