# Generated by Django 4.1.1 on 2022-12-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='documento',
            field=models.FileField(default='', upload_to='docs/% Y/% m/% d/'),
        ),
    ]
