# Generated by Django 4.1.1 on 2022-12-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_documento_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='documento',
            field=models.FileField(default='', upload_to='docs/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='fecha',
            field=models.DateField(),
        ),
    ]
