# Generated by Django 4.1.1 on 2022-09-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='img_url',
        ),
        migrations.AddField(
            model_name='monitor',
            name='img',
            field=models.ImageField(null=True, upload_to='fotos/'),
        ),
    ]
