# Generated by Django 4.1.1 on 2022-09-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitores', '0003_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='img',
            field=models.ImageField(null=True, upload_to='monitores/static/monitores/resources/fotos'),
        ),
    ]
