# Generated by Django 4.1.1 on 2022-10-18 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitores', '0004_remove_grupo_monis_monitor_grupos_alter_monitor_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='edad_max',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='edad_min',
        ),
    ]
