# Generated by Django 4.1.1 on 2022-10-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_image_remove_postimage_post_delete_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='route',
        ),
        migrations.AddField(
            model_name='image',
            name='image_path',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
