# Generated by Django 4.1.1 on 2022-10-03 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0006_remove_image_image_path_image_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(default=datetime.date)),
            ],
        ),
        migrations.CreateModel(
            name='Año',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagenes', models.FileField(null=True, upload_to='galeria/')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='año',
            name='grupos',
            field=models.ManyToManyField(to='galeria.grupo'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='fotos',
            field=models.ManyToManyField(to='galeria.imagen'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='grupos',
            field=models.ManyToManyField(to='galeria.grupo'),
        ),
    ]
