# Generated by Django 4.1.1 on 2022-10-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0007_actividad_año_grupo_imagen_delete_image_año_grupos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagen',
            old_name='imagenes',
            new_name='img',
        ),
        migrations.AlterField(
            model_name='año',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
