# Generated by Django 4.1.1 on 2022-10-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0008_rename_imagenes_imagen_img_alter_año_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='img',
            field=models.ImageField(null=True, upload_to='galeria/'),
        ),
    ]
