# Generated by Django 4.1.1 on 2022-10-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0010_alter_imagen_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='img',
        ),
        migrations.AddField(
            model_name='imagen',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
