# Generated by Django 4.1.1 on 2022-10-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0011_remove_imagen_img_imagen_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='image',
            field=models.ImageField(max_length=200, null=True, upload_to='galeria/'),
        ),
    ]
