# Generated by Django 4.1.1 on 2022-10-03 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0012_alter_imagen_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagen',
            old_name='image',
            new_name='img',
        ),
    ]
