# Generated by Django 4.1.1 on 2022-10-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0013_rename_image_imagen_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='dia',
            field=models.CharField(max_length=20),
        ),
    ]
