# Generated by Django 4.1.1 on 2022-10-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0014_alter_actividad_dia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='grupos',
        ),
        migrations.AddField(
            model_name='grupo',
            name='actividades',
            field=models.ManyToManyField(to='galeria.actividad'),
        ),
    ]
