# Generated by Django 4.1.1 on 2022-10-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0015_remove_actividad_grupos_grupo_actividades'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='path',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='img',
            field=models.ImageField(max_length=200, null=True, upload_to=models.CharField(max_length=200, null=True)),
        ),
    ]
