# Generated by Django 4.1.1 on 2022-10-04 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0017_alter_imagen_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='fotos',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='actividades',
        ),
        migrations.AddField(
            model_name='actividad',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='galeria.grupo'),
        ),
        migrations.AddField(
            model_name='imagen',
            name='activiad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='galeria.actividad'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='nombre',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
