# Generated by Django 4.1.1 on 2022-10-04 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0018_remove_actividad_fotos_remove_grupo_actividades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='año',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='galeria.año'),
        ),
    ]
