# Generated by Django 4.1.1 on 2022-10-04 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0019_actividad_año'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='año',
        ),
        migrations.RemoveField(
            model_name='año',
            name='grupos',
        ),
        migrations.AddField(
            model_name='grupo',
            name='año',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='galeria.año'),
        ),
    ]
