# Generated by Django 4.1.1 on 2022-10-04 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0020_remove_actividad_año_remove_año_grupos_grupo_año'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagen',
            old_name='activiad',
            new_name='actividad',
        ),
    ]
