# Generated by Django 4.1.1 on 2022-10-18 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0021_rename_activiad_imagen_actividad'),
    ]

    operations = [
    ]
